In [2]:
import numpy as np
arr=np.array((1,2,3,4))# crating array
print(arr)

[1 2 3 4]


In [5]:
arr=np.zeros(4) # zero D array
print(arr)

[0. 0. 0. 0.]


In [6]:
arr=np.ones(4) # 1 D array
print(arr)

[1. 1. 1. 1.]


In [7]:
arr = np.arange(1, 10, 2)
print("Arange:", arr) # arrange(give range into equally spaced step)


Arange: [1 3 5 7 9]


In [8]:
arr = np.linspace(0, 1, 5)
print("Linspace:", arr)# linspace(we give range and it give eqyally spaced)


Linspace: [0.   0.25 0.5  0.75 1.  ]


In [3]:
import numpy as np
arr = np.array([[1, 2, 3, 4],[4,5,6,7]]) # take transpose
print("Transpose:", arr.T)

Transpose: [[1 4]
 [2 5]
 [3 6]
 [4 7]]


In [10]:
arr = np.array([1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12])# convert 1D array to 2D array

newarr = arr.reshape(4, 3)

print(newarr)

[[ 1  2  3]
 [ 4  5  6]
 [ 7  8  9]
 [10 11 12]]


In [11]:
arr = np.array([1, 2, 3, 4, 5, 6])
# it spilt the array
newarr = np.array_split(arr, 3)

print(newarr)

[array([1, 2]), array([3, 4]), array([5, 6])]


In [12]:
arr = np.array([3, 2, 0, 1])
# it sort the array
print(np.sort(arr))

[0 1 2 3]


In [13]:
arr1 = np.array([1, 2, 3])

arr2 = np.array([4, 5, 6])
# concatenate(convert two 1D array into one array)
arr = np.concatenate((arr1, arr2))

print(arr)

[1 2 3 4 5 6]


In [14]:
arr = np.array([2, 4, 4, 6, 8, 8, 10])
np.unique(arr) # unique ( do not repeat values)

array([ 2,  4,  6,  8, 10])

In [8]:
arr = np.array([2, 4, 4, 6, 8, 8, 10])
print(np.max(arr)) # find maximum value
print(np.min(arr))# find minimum value

10
2


In [10]:
print(np.full((3,3),1)) #full matrix

[[1 1 1]
 [1 1 1]
 [1 1 1]]


In [13]:
arr=np.array([2,3,5,10,45,60]) # where ( we can use conditions)
print(np.where(arr>5,"pass","fail"))

['fail' 'fail' 'fail' 'pass' 'pass' 'pass']


In [16]:
arr=np.array([[1,2,3],[4,5,6,]]) # creatng 2D array
print(arr)

[[1 2 3]
 [4 5 6]]


In [17]:
arr=np.array([[[1,2,3],[4,5,6,]],[[6,9,7],[1,0,4]]]) # creatng 3D array
print(arr)

[[[1 2 3]
  [4 5 6]]

 [[6 9 7]
  [1 0 4]]]


In [18]:
a1=np.array([1,4,5,6])# vstack(convert two 1D in 2D array)k
a2=np.array([7,0,3,1])
combined=np.vstack((a1,a2))
print (combined)

[[1 4 5 6]
 [7 0 3 1]]


In [21]:
a1=np.array([1,4,5,6])# stack(convert two 2D in 3D array)
a2=np.array([7,0,3,1])
a3=np.array([1,4,5,6])
a4=np.array([7,0,3,1])
combined=np.vstack((a1,a2))
combined1=np.vstack((a3,a4))
combined2=np.stack((combined,combined1))
print (combined2)

[[[1 4 5 6]
  [7 0 3 1]]

 [[1 4 5 6]
  [7 0 3 1]]]


In [24]:
arr = np.array([1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12])# reshape 1D array into 3D array)

newarr = arr.reshape(3, 2, 2)

print(newarr)

[[[ 1  2]
  [ 3  4]]

 [[ 5  6]
  [ 7  8]]

 [[ 9 10]
  [11 12]]]


In [37]:
arr=np.array([[1,2,3,4,5,6],[7,8,9,10,11,12]])#reshape 2D array to 3D array
newarr=arr.reshape(2,3,2)
print(newarr)

[[[ 1  2]
  [ 3  4]
  [ 5  6]]

 [[ 7  8]
  [ 9 10]
  [11 12]]]


In [39]:
arr=np.array([[1,2,3,4,5,6],[7,8,9,10,11,12]])# flatten(convert 2D array to 1D array)
print(arr.flatten())

[ 1  2  3  4  5  6  7  8  9 10 11 12]
